server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=GreenSlotDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

greeenslot:
  app:
    jwtSecret: "======================GreenSlot=Spring=Boot=Secret=Key=For=JWT=Generation=Must=Be=Long======================"
    jwtExpirationMs: 86400000 # 24 hours
